const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';
const GET_DM_FROM_LOCALSTORAGE = 'GET_DM_FROM_LOCALSTORAGE';

const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';

export { TOGGLE_DARK_MODE, GET_DM_FROM_LOCALSTORAGE, LOGOUT, LOGIN };
